config/routes.rb
CrackIt::Application.routes.draw do
  resources :sessions

  devise_for :users

  root 'home#dashboard'

resources :home do
  collection do
    get 'login'
    get 'dashboard'
  end
end

resources :interview do
  collection do
    post 'setup'
    post 'room'
    post 'save_interview'
  end
end

  

end

app/models/code.rb
class Code < ActiveRecord::Base
	belongs_to :session
end

app/models/personal_note.rb
class PersonalNote < ActiveRecord::Base
	belongs_to :session
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :user, foreign_key: "creator_id"
	has_many :codes
	has_many :videos
	has_many :personal_notes

	def self.creator
		User.find(self.creator_id)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sessions, foreign_key: "creator_id"
  has_many :personal_notes
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :check_logged_in, except: [:login]

	def login
	end

	def dashboard
		sess = Session.where(:creator_id => current_user.id )
		@old_sesh = sess.select {|one| one.time < Time.now}
		@new_sesh = sess.select {|one| one.time > Time.now}
	end


	private
	def check_logged_in
		if current_user.nil?
			redirect_to login_home_index_path
		end
	end
end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController
	def setup
		@session = Session.find(params["data"]["id"])
	end

	def room
	end

	def save_interview
		@session = Session.find(params["sesh_id"])
		@session.codes.create(:code_text => params["code"])
		@session.personal_notes.create(:note => params["note"])
		render :nothing => true
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_session, only: [:show, :edit, :update, :destroy]

  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.all
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
  end

  # GET /sessions/new
  def new
    @session = Session.new
  end

  # GET /sessions/1/edit
  def edit
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.new(session_params)

    respond_to do |format|
      if @session.save
        format.html { redirect_to @session, notice: 'Session was successfully created.' }
        format.json { render action: 'show', status: :created, location: @session }
      else
        format.html { render action: 'new' }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sessions/1
  # PATCH/PUT /sessions/1.json
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { redirect_to @session, notice: 'Session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    @session.destroy
    respond_to do |format|
      format.html { redirect_to sessions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = Session.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params.require(:session).permit(:creator_id, :"time(1i)",:"time(2i)",:"time(3i)",:"time(4i)",:"time(5i)", :note, :interviewer_email, :interviewee_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/_login_links.html.erb
<%resource_name = "user"%>

<%= link_to "Sign in", new_session_path(resource_name) %><br />

<%= link_to "Sign up", new_registration_path(resource_name) %><br />

<%= link_to "Forgot your password?", new_password_path(resource_name) %><br />

app/views/home/dashboard.html.erb
<div class="dashboard">
  <h1>Dashboard</h1>
  <div class ="current-int inlineb scroll-y">
    <h5>Current Interviews </h5>
    <% @new_sesh.each do |sesh|%>
    <div class="sesh">
      <div class= "sec-width inlineb">
        <div class = "inlineb time">Time: <%= sesh.time.strftime("%b %d, %Y")%></div>
        <div class = "inlineb note scroll-y">Note: <%= sesh.note%></div>
      </div>
      <div class="sec-width inlineb">
        <div class = "inlineb inter">Interviewer: <%= sesh.interviewer_email%></div>
        <div class = "inlineb intee"> Interviewee: <%= sesh.interviewee_email%></div>
        <div class = "inlineb but"><%= button_to("Start", { controller: "interview", action: "setup", data: {:id => sesh.id}, form: { "data-type" => "json" }},{:class => "btn-small inlineb"})%> | <%= link_to 'View', sesh, {:class => "inlineb btn"} %></div>

      </div>
    </div>
    <hr>
    <% end%>
  </div>
  <div class ="create-int inlineb">
    <%= form_for(Session.new, :url => sessions_path, :method => "post", :html => {:class => "form-horizontal"}) do |f| %>
      <%= f.hidden_field :creator_id, :value => current_user.id %>

      <div> <span>Date: </span>
      <%= f.datetime_select :time%></div>
      <br/>

      <div> <span>Note: </span>
      <%= f.text_area :note, :class => "bck" %></div>
      <br/>

      <div><span>Interviewer Email: </span>
      <%= f.email_field :interviewer_email, :class => "bck" %></div>
      <br/>

      <div><span>Interviewee Email: </span>
      <%= f.email_field :interviewee_email, :class => "bck" %></div>
      <br/>

      <div class="actions">
        <%= f.submit "Create Interview",  :class => "btn-small"%>
      </div>
    <% end %>
  </div>

  <div class="old-int inlineb ">
    <h5>Old Interviews </h5>
    <table class = "table table-striped">
      <thead>
        <tr>
          <th>Time</th>
          <th>Note</th>
          <th>Interviewer Email</th>
          <th>Interviewee Email</th>
          <th>View</th>
        </tr>
      </thead>

      <tbody class="scroll-y">
        <% @old_sesh.each do |session| %>
          <tr>
            <td><%= session.time.strftime("%b %d, %Y")%></td>
            <td><%= session.note%></td>
            <td><%= session.interviewer_email%></td>
            <td><%= session.interviewee_email%></td>
            <td><%= link_to 'View', session %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/login.html.erb
<div class="wrapper" >

    <div class="top-font"> Crackit </div>

    <div class="coming-soon"> COMING SOON </div>

    <div class="mission-statement">
            (Building a community for people to learn and prepare for technical interviews)
    </div>
    <h2>Sign in</h2>

<%= form_for(User.new, :url => user_session_path) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>

  <div><%= f.submit "Sign in" %></div>
  <%= link_to "Forgot your password?", new_password_path("user") %><br />
<% end %>

<h2>Sign up</h2>

<%= form_for(User.new, :url => user_registration_path) do |f| %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>


<div class="contact">
    Contact us: crackwithus@gmail.com
</div>

app/views/interview/room.html.erb
<div class="int-room inlineb">
	<h1>Interview Room (<%= params["role"]%>)</h1>
	<div class="int-main-left inlineb">
		<div class="int-vid inlineb">
			<%= image_tag("video_placeholder.jpg")%>
		</div>
		<div class="int-code inlineb">
			<textarea class = "interview-code" placeholder='Code Here'></textarea>
		</div>
	</div>
	<div class="int-main-right inlineb int-note">
		<textarea class = "personal-notes" placeholder='Personal Notes Here'></textarea>
	</div>

	<button class="btn-small save-sesh" data-id= "<%= current_user.id%>" data-sesh = "<%= params['session_id'] %>">Save Session</button>
</div>

app/views/interview/setup.html.erb
<div class="int-setup inlineb">
	<h1>Set Up</h1>
	<div class="setup-form inlineb">
		<%= form_tag(:controller => "interview",:action => "room") do %>
			<h4>Choose your role: </h4>
			<%= hidden_field_tag(:session_id, @session.id) %>
			<div>
				<%= radio_button_tag(:role, "Interviewer", :class => "inlineb") %>
				<%= label_tag(:role_Interviewer, "Interviewer", :class => "inlineb") %>
			</div>
			<div>
				<%= radio_button_tag(:role, "Interviewee", :class => "inlineb") %>
				<%= label_tag(:role_Interviewee, "Interviewee", :class => "inlineb") %>
			</div>
			<%= submit_tag("Enter Interview Room", :class => "btn-small") %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrackIt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
	<p class="alert alert-notice"><%= notice%></p>
<% end %>
<% if alert%>
	<p class="alert alert-error"><%= alert%></p>
<%end%>

<%= render 'partials/navbar' %>
<%= yield %>

</body>
</html>

app/views/partials/_navbar.html.erb
<!-- Navigation bar -->
<header>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">    
            <%if current_user %>    
            <ul class="nav navbar-nav pull-right">
                <li><%= link_to('Home',root_path )%> </li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email%>
                    <b class="caret" style="color:#ffffff"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to('Security Settings',edit_user_registration_path, method: :get )%> </li>
                    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  </li>
                </ul>
                </li>
            </ul>   
            <%end%> 
            <div class = "crack">
                <h6><%= link_to "Crack It", root_path, id: "logo"%></h6>
            </div>        
        </div>
    </div>
</div>
</header>